version: "3"
services:
  react-app:
    build: 
      context: ./crm-frontend
      dockerfile: Dockerfile
    image: react-app-production:${ENV}
    restart: unless-stopped
    ports: 
      - "80:80"
    networks:
      - mern-app
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - api-server
  
  api-server:
    build: 
      context: ./crm-backend
      dockerfile: Dockerfile
    image: api-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: ./crm-backend/config/${ENV}.env
    networks:
      - mern-app
    depends_on:
      - redis
  
  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
