version: "3.8"
services:

  client:
    build: 
      context: ./crm-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./crm-frontend/src:/usr/app/src
      - ./crm-frontend/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  db:
      image: mongo:latest
      ports:
        - 27017:27017
      networks:
        - mern-network
      volumes:
        - mongo-data:/data/db
    
  server:
    build:
      context: ./crm-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - ./crm-backend/src:/usr/app/src
    depends_on:
      - db
    environment:
      - NODE_ENV=production 
      - MONGO_URI=mongodb+srv://capstone:Y0uD3pl0y@cluster0.zncig.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - CLIENT= http://localhost:3000
      - REDIS_URL= redis://localhost:6379
      - JWT_ACCESS_SECRET=lwsjerjkjkhashfkjasdfajksh
      - JWT_REFRESH_SECRET=dlsgjkldhsgkjhskghkadshgkjhdkghjsdhg
      - REDIS_HOST=' redis-cache' 
      - REDIS_PORT=6379
  
  cache:
    image: "redis:alpine"
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379
    #command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
        - mern-network  

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  cache:
    driver: local