name: Build

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd crm-frontend && docker build . --file Dockerfile --tag crm-frontend:$(date +%s)
           
